export const ADMIN_GET_CHANNELS_ATTEMPT = 'ADMIN_GET_CHANNEL_CATEGORIES_ATTEMPT';
export const ADMIN_GET_CHANNELS_SUCCESS = 'ADMIN_GET_CHANNEL_CATEGORIES_SUCCESS';
export const ADMIN_GET_CHANNELS_FAILED = 'ADMIN_GET_CHANNEL_CATEGORIES_FAILED';

export const ADMIN_ADD_CHANNEL_ATTEMPT = 'ADMIN_ADD_CHANNEL_CATEGORY_ATTEMPT';
export const ADMIN_ADD_CHANNEL_SUCCESS = 'ADMIN_ADD_CHANNEL_CATEGORY_SUCCESS';
export const ADMIN_ADD_CHANNEL_FAILED = 'ADMIN_ADD_CHANNEL_CATEGORY_FAILED';

export const ADMIN_EDIT_CHANNEL_ATTEMPT = 'ADMIN_EDIT_CHANNEL_CATEGORY_ATTEMPT';
export const ADMIN_EDIT_CHANNEL_SUCCESS = 'ADMIN_EDIT_CHANNEL_CATEGORY_SUCCESS';
export const ADMIN_EDIT_CHANNEL_FAILED = 'ADMIN_EDIT_CHANNEL_CATEGORY_FAILED';

export const ADMIN_DELETE_CHANNEL_ATTEMPT = 'ADMIN_DELETE_CHANNEL_CATEGORY_ATTEMPT';
export const ADMIN_DELETE_CHANNEL_SUCCESS = 'ADMIN_DELETE_CHANNEL_CATEGORY_SUCCESS';
export const ADMIN_DELETE_CHANNEL_FAILED = 'ADMIN_DELETE_CHANNEL_CATEGORY_FAILED';
