
export const ADMIN_GET_CITIES_ATTEMPT = 'ADMIN_GET_CITIES_ATTEMPT';
export const ADMIN_GET_CITIES_SUCCESS = 'ADMIN_GET_CITIES_SUCCESS';
export const ADMIN_GET_CITIES_FAILED = 'ADMIN_GET_CITIES_FAILED';

export const ADMIN_ADD_CITY_ATTEMPT = 'ADMIN_ADD_CITY_ATTEMPT';
export const ADMIN_ADD_CITY_SUCCESS = 'ADMIN_ADD_CITY_SUCCESS';
export const ADMIN_ADD_CITY_FAILED = 'ADMIN_ADD_CITY_FAILED';

export const ADMIN_EDIT_CITY_ATTEMPT = 'ADMIN_EDIT_CITY_ATTEMPT';
export const ADMIN_EDIT_CITY_SUCCESS = 'ADMIN_EDIT_CITY_SUCCESS';
export const ADMIN_EDIT_CITY_FAILED = 'ADMIN_EDIT_CITY_FAILED';

export const ADMIN_DELETE_CITY_ATTEMPT = 'ADMIN_DELETE_CITY_ATTEMPT';
export const ADMIN_DELETE_CITY_SUCCESS = 'ADMIN_DELETE_CITY_SUCCESS';
export const ADMIN_DELETE_CITY_FAILED = 'ADMIN_DELETE_CITY_FAILED';
