export const ADMIN_GET_ENTITY_TYPES_ATTEMPT = 'ADMIN_GET_ENTITY_TYPES_ATTEMPT';
export const ADMIN_GET_ENTITY_TYPES_SUCCESS = 'ADMIN_GET_ENTITY_TYPES_SUCCESS';
export const ADMIN_GET_ENTITY_TYPES_FAILED = 'ADMIN_GET_ENTITY_TYPES_FAILED';

export const ADMIN_ADD_ENTITY_TYPE_ATTEMPT = 'ADMIN_ADD_ENTITY_TYPE_ATTEMPT';
export const ADMIN_ADD_ENTITY_TYPE_SUCCESS = 'ADMIN_ADD_ENTITY_TYPE_SUCCESS';
export const ADMIN_ADD_ENTITY_TYPE_FAILED = 'ADMIN_ADD_ENTITY_TYPE_FAILED';

export const ADMIN_EDIT_ENTITY_TYPE_ATTEMPT = 'ADMIN_EDIT_ENTITY_TYPE_ATTEMPT';
export const ADMIN_EDIT_ENTITY_TYPE_SUCCESS = 'ADMIN_EDIT_ENTITY_TYPE_SUCCESS';
export const ADMIN_EDIT_ENTITY_TYPE_FAILED = 'ADMIN_EDIT_ENTITY_TYPE_FAILED';

export const ADMIN_DELETE_ENTITY_TYPE_ATTEMPT = 'ADMIN_DELETE_ENTITY_TYPE_ATTEMPT';
export const ADMIN_DELETE_ENTITY_TYPE_SUCCESS = 'ADMIN_DELETE_ENTITY_TYPE_SUCCESS';
export const ADMIN_DELETE_ENTITY_TYPE_FAILED = 'ADMIN_DELETE_ENTITY_TYPE_FAILED';
