export const ADMIN_GET_LANGUAGES_ATTEMPT = 'ADMIN_GET_LANGUAGES_ATTEMPT';
export const ADMIN_GET_LANGUAGES_SUCCESS = 'ADMIN_GET_LANGUAGES_SUCCESS';
export const ADMIN_GET_LANGUAGES_FAILED = 'ADMIN_GET_LANGUAGES_FAILED';

export const ADMIN_ADD_LANGUAGE_ATTEMPT = 'ADMIN_ADD_LANGUAGE_ATTEMPT';
export const ADMIN_ADD_LANGUAGE_SUCCESS = 'ADMIN_ADD_LANGUAGE_SUCCESS';
export const ADMIN_ADD_LANGUAGE_FAILED = 'ADMIN_ADD_LANGUAGE_FAILED';

export const ADMIN_EDIT_LANGUAGE_ATTEMPT = 'ADMIN_EDIT_LANGUAGE_ATTEMPT';
export const ADMIN_EDIT_LANGUAGE_SUCCESS = 'ADMIN_EDIT_LANGUAGE_SUCCESS';
export const ADMIN_EDIT_LANGUAGE_FAILED = 'ADMIN_EDIT_LANGUAGE_FAILED';

export const ADMIN_DELETE_LANGUAGE_ATTEMPT = 'ADMIN_DELETE_LANGUAGE_ATTEMPT';
export const ADMIN_DELETE_LANGUAGE_SUCCESS = 'ADMIN_DELETE_LANGUAGE_SUCCESS';
export const ADMIN_DELETE_LANGUAGE_FAILED = 'ADMIN_DELETE_LANGUAGE_FAILED';