
export const ADMIN_GET_NATIONALITIES_ATTEMPT = 'ADMIN_GET_NATIONALITIES_ATTEMPT';
export const ADMIN_GET_NATIONALITIES_SUCCESS = 'ADMIN_GET_NATIONALITIES_SUCCESS';
export const ADMIN_GET_NATIONALITIES_FAILED = 'ADMIN_GET_NATIONALITIES_FAILED';

export const ADMIN_ADD_NATIONALITY_ATTEMPT = 'ADMIN_ADD_NATIONALITY_ATTEMPT';
export const ADMIN_ADD_NATIONALITY_SUCCESS = 'ADMIN_ADD_NATIONALITY_SUCCESS';
export const ADMIN_ADD_NATIONALITY_FAILED = 'ADMIN_ADD_NATIONALITY_FAILED';

export const ADMIN_EDIT_NATIONALITY_ATTEMPT = 'ADMIN_EDIT_NATIONALITY_ATTEMPT';
export const ADMIN_EDIT_NATIONALITY_SUCCESS = 'ADMIN_EDIT_NATIONALITY_SUCCESS';
export const ADMIN_EDIT_NATIONALITY_FAILED = 'ADMIN_EDIT_NATIONALITY_FAILED';

export const ADMIN_DELETE_NATIONALITY_ATTEMPT = 'ADMIN_DELETE_NATIONALITY_ATTEMPT';
export const ADMIN_DELETE_NATIONALITY_SUCCESS = 'ADMIN_DELETE_NATIONALITY_SUCCESS';
export const ADMIN_DELETE_NATIONALITY_FAILED = 'ADMIN_DELETE_NATIONALITY_FAILED';
