export const ADMIN_GET_REGIONS_ATTEMPT = 'ADMIN_GET_REGIONS_ATTEMPT';
export const ADMIN_GET_REGIONS_SUCCESS = 'ADMIN_GET_REGIONS_SUCCESS';
export const ADMIN_GET_REGIONS_FAILED = 'ADMIN_GET_REGIONS_FAILED';

export const ADMIN_ADD_REGION_ATTEMPT = 'ADMIN_ADD_REGION_ATTEMPT';
export const ADMIN_ADD_REGION_SUCCESS = 'ADMIN_ADD_REGION_SUCCESS';
export const ADMIN_ADD_REGION_FAILED = 'ADMIN_ADD_REGION_FAILED';

export const ADMIN_EDIT_REGION_ATTEMPT = 'ADMIN_EDIT_REGION_ATTEMPT';
export const ADMIN_EDIT_REGION_SUCCESS = 'ADMIN_EDIT_REGION_SUCCESS';
export const ADMIN_EDIT_REGION_FAILED = 'ADMIN_EDIT_REGION_FAILED';

export const ADMIN_DELETE_REGION_ATTEMPT = 'ADMIN_DELETE_REGION_ATTEMPT';
export const ADMIN_DELETE_REGION_SUCCESS = 'ADMIN_DELETE_REGION_SUCCESS';
export const ADMIN_DELETE_REGION_FAILED = 'ADMIN_DELETE_REGION_FAILED';