export const ROUTES = {
    LOGIN: '/login',
    LOGOUT: '/logout',
    DASHBOARD: '/',
    GOVENTS: '/content/gov-ents',
    QUESTION_BANK: '/content/question-bank',
    SURVEY_BANK: '/content/survey-bank',
    NATIONALITIES: '/admin/categories/nationalities',
    LANGUAGES: '/admin/categories/langugaes',
    REGIONS: '/admin/categories/regions',
    CITIES: '/admin/categories/cities',
    CHANNELCATEGORIES: '/admin/categories/channel-categories',
    CHANNELTYPES: '/admin/categories/channel-types',
    ENTITYTYPES: '/admin/categories/entity-types',
    QUESTIONCATEGORY: '/admin/categories/question-category',
    SETTINGS: '/admin/settings',
    USERS: '/admin/users',
    SERVICES: '/content/services',
    ADDSERVICE: '/content/services/add-service',
    CHANNELS: '/content/channels',
    SECTORS: '/content/sectors',
    ADDSECTOR: '/content/sectors/add',
    EDITSECTOR: '/content/sectors/edit/:sectorId',
    ENTITIES: '/content/entities',
    ADDENTITY: '/content/entities/add',
    EDITENTITY: '/content/entities/edit/:entityId',
    
};
