export const ROUTES = {
    LOGIN: '/login',
    LOGOUT: '/logout',
    DASHBOARD: '/',
    GOVENTS: '/content/gov-ents',
    QUESTION_BANK: '/content/question-bank',
    SURVEY_BANK: '/content/survey-bank',
    NATIONALITIES: '/admin/categories/nationalities',
    LANGUAGES: '/admin/categories/langugaes',
    REGIONS: '/admin/categories/regions',
    CITIES: '/admin/categories/cities',
    CHANNELS: '/admin/categories/channels',
    SETTINGS: '/admin/settings',
    USERS: '/admin/users',
}