export const ADMIN_GET_ENTITIES_ATTEMPT = 'ADMIN_GET_ENTITIES_ATTEMPT';
export const ADMIN_GET_ENTITIES_SUCCESS = 'ADMIN_GET_ENTITIES_SUCCESS';
export const ADMIN_GET_ENTITIES_FAILED = 'ADMIN_GET_ENTITIES_FAILED';

export const ADMIN_ADD_ENTITY_ATTEMPT = 'ADMIN_ADD_ENTITY_ATTEMPT';
export const ADMIN_ADD_ENTITY_SUCCESS = 'ADMIN_ADD_ENTITY_SUCCESS';
export const ADMIN_ADD_ENTITY_FAILED = 'ADMIN_ADD_ENTITY_FAILED';

export const ADMIN_EDIT_ENTITY_ATTEMPT = 'ADMIN_EDIT_ENTITY_ATTEMPT';
export const ADMIN_EDIT_ENTITY_SUCCESS = 'ADMIN_EDIT_ENTITY_SUCCESS';
export const ADMIN_EDIT_ENTITY_FAILED = 'ADMIN_EDIT_ENTITY_FAILED';

export const ADMIN_DELETE_ENTITY_ATTEMPT = 'ADMIN_DELETE_ENTITY_ATTEMPT';
export const ADMIN_DELETE_ENTITY_SUCCESS = 'ADMIN_DELETE_ENTITY_SUCCESS';
export const ADMIN_DELETE_ENTITY_FAILED = 'ADMIN_DELETE_ENTITY_FAILED';
