export const ADMIN_GET_SERVICES_ATTEMPT = 'ADMIN_GET_SERVICES_ATTEMPT';
export const ADMIN_GET_SERVICES_SUCCESS = 'ADMIN_GET_SERVICES_SUCCESS';
export const ADMIN_GET_SERVICES_FAILED = 'ADMIN_GET_SERVICES_FAILED';

export const ADMIN_ADD_SERVICE_ATTEMPT = 'ADMIN_ADD_SERVICE_ATTEMPT';
export const ADMIN_ADD_SERVICE_SUCCESS = 'ADMIN_ADD_SERVICE_SUCCESS';
export const ADMIN_ADD_SERVICE_FAILED = 'ADMIN_ADD_SERVICE_FAILED';

export const ADMIN_EDIT_SERVICE_ATTEMPT = 'ADMIN_EDIT_SERVICE_ATTEMPT';
export const ADMIN_EDIT_SERVICE_SUCCESS = 'ADMIN_EDIT_SERVICE_SUCCESS';
export const ADMIN_EDIT_SERVICE_FAILED = 'ADMIN_EDIT_SERVICE_FAILED';

export const ADMIN_DELETE_SERVICE_ATTEMPT = 'ADMIN_DELETE_SERVICE_ATTEMPT';
export const ADMIN_DELETE_SERVICE_SUCCESS = 'ADMIN_DELETE_SERVICE_SUCCESS';
export const ADMIN_DELETE_SERVICE_FAILED = 'ADMIN_DELETE_SERVICE_FAILED';
