export const ADMIN_GET_USERS_ATTEMPT = 'ADMIN_GET_USERS_ATTEMPT';
export const ADMIN_GET_USERS_SUCCESS = 'ADMIN_GET_USERS_SUCCESS';
export const ADMIN_GET_USERS_FAILED = 'ADMIN_GET_USERS_FAILED';

export const ADMIN_ADD_USER_ATTEMPT = 'ADMIN_ADD_USER_ATTEMPT';
export const ADMIN_ADD_USER_SUCCESS = 'ADMIN_ADD_USER_SUCCESS';
export const ADMIN_ADD_USER_FAILED = 'ADMIN_ADD_USER_FAILED';

export const ADMIN_EDIT_USER_ATTEMPT = 'ADMIN_EDIT_USER_ATTEMPT';
export const ADMIN_EDIT_USER_SUCCESS = 'ADMIN_EDIT_USER_SUCCESS';
export const ADMIN_EDIT_USER_FAILED = 'ADMIN_EDIT_USER_FAILED';

export const ADMIN_DELETE_USER_ATTEMPT = 'ADMIN_DELETE_USER_ATTEMPT';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAILED = 'ADMIN_DELETE_USER_FAILED';
