export const ADMIN_GET_SECTORS_ATTEMPT = 'ADMIN_GET_SECTORS_ATTEMPT';
export const ADMIN_GET_SECTORS_SUCCESS = 'ADMIN_GET_SECTORS_SUCCESS';
export const ADMIN_GET_SECTORS_FAILED = 'ADMIN_GET_SECTORS_FAILED';

export const ADMIN_ADD_SECTOR_ATTEMPT = 'ADMIN_ADD_SECTOR_ATTEMPT';
export const ADMIN_ADD_SECTOR_SUCCESS = 'ADMIN_ADD_SECTOR_SUCCESS';
export const ADMIN_ADD_SECTOR_FAILED = 'ADMIN_ADD_SECTOR_FAILED';

export const ADMIN_EDIT_SECTOR_ATTEMPT = 'ADMIN_EDIT_SECTOR_ATTEMPT';
export const ADMIN_EDIT_SECTOR_SUCCESS = 'ADMIN_EDIT_SECTOR_SUCCESS';
export const ADMIN_EDIT_SECTOR_FAILED = 'ADMIN_EDIT_SECTOR_FAILED';

export const ADMIN_DELETE_SECTOR_ATTEMPT = 'ADMIN_DELETE_SECTOR_ATTEMPT';
export const ADMIN_DELETE_SECTOR_SUCCESS = 'ADMIN_DELETE_SECTOR_SUCCESS';
export const ADMIN_DELETE_SECTOR_FAILED = 'ADMIN_DELETE_SECTOR_FAILED';
